version: '3.8'

services:
  postgresql:
    ports:
      - '5432:5432'
    image: bitnami/postgresql
    env_file:
      - .env
    volumes:
      - postgresql_data:/bitnami/postgresql
      - ./app/db:/docker-entrypoint-initdb.d

volumes:
  postgresql_data: